name: prototype2
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/icons/barbells.png
    - assets/icons/cableMachine.png
    - assets/icons/cardio.png
    - assets/icons/dumbbells.png
    - assets/icons/pullUpBar.png
    - assets/icons/resistanceBands.png
    - assets/icons/weightMachine.png 
    - assets/icons/athleticPerformance.png
    - assets/icons/newExercises.png
    - assets/icons/feelBetter.png
    - assets/icons/yogaMat.png
    - assets/icons/getStronger.png
    - assets/icons/loseWeight.png
    - assets/icons/increaseMuscleMass.png
    - assets/icons/maleSign.png
    - assets/icons/femaleSign.png
    - assets/images/abs.png
    - assets/images/back.png
    - assets/images/biceps.png
    - assets/images/calves.png
    - assets/images/chest.png
    - assets/images/forearms.png
    - assets/images/glutes.png
    - assets/images/hamstrings.png
    - assets/images/lowerBack.png
    - assets/images/neck.png
    - assets/images/quadriceps.png
    - assets/images/shoulders.png
    - assets/images/trapezius.png
    - assets/images/triceps.png
    - assets/images/wideGripPullUp.jpg
    - assets/animations/wideGripPullUp.gif
    - assets/images/barbellRow.png
    - assets/animations/barbellRow.gif
    - assets/images/latPulldown.jpg
    - assets/animations/latPulldown.gif
    - assets/images/tricepPushdown.jpg
    - assets/animations/tricepPushdown.gif
    - assets/images/overheadDumbbellTricepExtension.jpg
    - assets/animations/overheadDumbbellTricepExtension.gif
    - assets/images/closeGripBenchPress.jpg
    - assets/animations/closeGripBenchPress.gif
    - assets/images/inclineBenchPress.jpg
    - assets/animations/inclineBenchPress.gif
    - assets/images/benchPress.jpg
    - assets/animations/benchPress.gif
    - assets/images/declineBenchPress.jpg
    - assets/animations/declineBenchPress.gif
    - assets/images/chinUp.jpg
    - assets/animations/chinUp.gif
    - assets/images/barbellCurl.jpg
    - assets/animations/barbellCurl.gif
    - assets/images/inclineDumbbellCurl.jpg
    - assets/animations/inclineDumbbellCurl.gif
    - assets/images/barbellShrug.jpg
    - assets/animations/barbellShrug.gif
    - assets/images/dumbbellShrugs.jpg
    - assets/animations/dumbbellShrugs.gif
    - assets/images/behindTheNeckPullUp.jpg
    - assets/animations/behindTheNeckPullUp.gif
    - assets/images/declineDumbbellPress.jpg
    - assets/animations/declineDumbbellPress.gif
    - assets/images/barbellSkullCrusher.jpg
    - assets/animations/barbellSkullCrusher.gif
    - assets/images/dumbbellSkullCrusher.jpg
    - assets/animations/dumbbellSkullCrusher.gif
    - assets/images/inclineDumbbellPress.jpg
    - assets/animations/inclineDumbbellPress.gif
    - assets/images/dumbbellBenchPress.jpg
    - assets/animations/dumbbellBenchPress.gif
    - assets/images/cableLateralRaise.jpg
    - assets/animations/cableLateralRaise.gif
    - assets/images/dumbbellLateralRaise.jpg
    - assets/animations/dumbbellLateralRaise.gif
    - assets/images/seatedDumbbellPress.jpg
    - assets/animations/seatedDumbbellPress.gif
    - assets/images/crunches.jpg
    - assets/animations/crunches.gif
    - assets/images/declineSitUp.jpg
    - assets/animations/declineSitUp.gif
    - assets/images/hangingKneeRaise.jpg
    - assets/animations/hangingKneeRaise.gif
    - assets/images/hyperextensions.jpg
    - assets/animations/hyperextensions.gif
    - assets/images/goodMornings.jpg
    - assets/animations/goodMornings.gif
    - assets/images/machineBackExtension.jpg
    - assets/animations/machineBackExtension.gif
    - assets/images/gluteBridge.jpg
    - assets/animations/gluteBridge.gif
    - assets/images/machineHipAbduction.jpg
    - assets/animations/machineHipAbduction.gif
    - assets/images/sumoDeadlift.jpg
    - assets/animations/sumoDeadlift.gif
    - assets/images/nordicHipHinge.jpg
    - assets/animations/nordicHipHinge.gif
    - assets/images/lyingLegCurl.jpg
    - assets/animations/lyingLegCurl.gif
    - assets/images/romanianDeadlift.jpg
    - assets/animations/romanianDeadlift.gif
    - assets/images/pistolSquat.jpg
    - assets/animations/pistolSquat.gif
    - assets/images/frontSquat.jpg
    - assets/animations/frontSquat.gif
    - assets/images/machineHackSquat.jpg
    - assets/animations/machineHackSquat.gif
    - assets/images/machineCalfRaise.jpg
    - assets/animations/machineCalfRaise.gif
    - assets/images/machineSeatedCalfRaise.jpg
    - assets/animations/machineSeatedCalfRaise.gif
    - assets/images/dumbbellCalfRaise.jpg
    - assets/animations/dumbbellCalfRaise.gif
    - assets/images/reverseBarbellCurl.jpg
    - assets/animations/reverseBarbellCurl.gif
    - assets/images/neckExtensions.jpg
    - assets/animations/neckExtensions.gif
    - assets/images/neckCurls.jpg
    - assets/animations/neckCurls.gif
    - assets/images/sideNeckCurls.jpg
    - assets/animations/sideNeckCurls.gif




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600



  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
